config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    path: '', # optional namespace or empty string for no space
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'secret',
      confirmation: 'verification',
      registration: 'register',
      sign_up: 'signup'
    }

  devise_scope :user do
    authenticated :user do
      root 'insureds#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  

  resources :insureds, only: %i[index new create show] do
    resources :contacts, only: %i[index new create show]
    resources :addresses
    resources :orders
  end
  resources :orders, only: %i[index]
  resources :insured_records, only: [:new, :create]
  resources :pre_opinions
  resources :opinions
  resources :doctors
  resources :providers
  resources :treatments
  resources :raw_materials
  # resources :sections, only: %i[new create]

  resources :users, only: %i[index new create edit update]
  
  get 'pages/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :insured

  validates :street, presence: true
  validates :interior_number, presence: true
  validates :outdoor_number, presence: true
  validates :postal_code, presence: true
  validates :suburb, presence: true
  validates :reference, presence: true

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :order
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :insured

  validates :name, presence: true
  validates :relation, presence: true
  validates :phone, presence: true
  validates :cell_phone, presence: true
  validates :email, presence: true
  validates :notes, presence: true

  accepts_nested_attributes_for :insured

end

app/models/contact_info.rb
class ContactInfo < ApplicationRecord
  belongs_to :insured
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    has_many :treatments
    has_many :insureds, through: :treatments
    
    validates :name, 
        :last_name, 
        :mother_last_name, 
        :mobile,
        :mail,
        presence: true 
    
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :order
end

app/models/insured.rb
class Insured < ApplicationRecord
    has_one :contact_info
    has_many :treatments
    has_many :doctors, through: :treatments
    
    has_many :contacts
    has_many :addresses
    has_many :orders
    
    validates :name, presence: true 
    validates :last_name, presence: true 
    validates :mother_last_name, presence: true 
    validates :gender, presence: true 
    validates :birth_date, presence: true 
    validates :policy, presence: true 
end

app/models/insured_record.rb
class InsuredRecord
    include ActiveModel::Model

    attr_accessor(
        :name, 
        :last_name, 
        :mother_last_name, 
        :gender, 
        :birth_date, 
        :street, 
        :interior_number, 
        :outdoor_number, 
        :postal_code, 
        :suburb
    )
    validates :name, presence: true 
    validates :last_name, presence: true 
    validates :mother_last_name, presence: true 
    validates :gender, presence: true 
    validates :birth_date, presence: true 
    validates :street, presence: true 
    validates :interior_number, presence: true 
    validates :outdoor_number, presence: true 
    validates :postal_code, presence: true 
    validates :suburb, presence: true 

    
    def save
        return false if invalid?

        ActiveRecord::Base.transaction do
            insured = Insured.create!(name: name, 
                last_name: last_name, mother_last_name: mother_last_name, 
                gender: gender, birth_date: birth_date)
            insured.create_contact_info!(
                street: street, 
                interior_number: interior_number, 
                outdoor_number: outdoor_number, 
                postal_code: postal_code, 
                suburb: suburb
            )
        end

        true

    rescue ActiveRecord::StatementInvalid => e
        # Handle exception that caused the transaction to fail
        # e.message and e.cause.message can be helpful
        errors.add(:base, e.message)
        false
    end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :order
  belongs_to :raw_material
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :insured
  has_many :comments
  has_many :documents
  
  has_many :items
  has_many :raw_materials, through: :items
  accepts_nested_attributes_for :raw_materials
end

app/models/provider.rb
class Provider < ApplicationRecord
    validates :business_name, presence: true 
    validates :tradename, presence: true
    validates :rfc, presence: true
    validates :address, presence: true
    validates :street, presence: true
    validates :suburb, presence: true
    validates :responsable, presence: true
    validates :responsible_phone, presence: true
    validates :email, presence: true
    validates :notification_mail, presence: true
    validates :general_description, presence: true
    
end

app/models/raw_material.rb
class RawMaterial < ApplicationRecord
  belongs_to :unit_measurement
  belongs_to :raw_material_group
  belongs_to :raw_material_family

  has_many :items
  has_many :orders, through: :items
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/section.rb
class Section < ApplicationRecord
    has_one :user
    
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  belongs_to :insured
  belongs_to :doctor
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :section
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  def index
    @providers = Provider.all
  end

  def new
    @provider = Provider.new
  end

  def create
    @provider = Provider.new provider_params
    if @provider.save
        return redirect_to providers_path
    end
    render :new
  end

  private
  def provider_params
    params.require(:provider).permit! 
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/providers/_form.html.erb
<%= form_for @provider, builder: CustomFormBuilder do |f| %>
    <%= f.form_error %>
    <div class="row">
        <div class="col-sm">
            <div class="card">
                <div class="card-header">
                    Datos del proveeder
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <%= f.label :business_name, class: 'bmd-label-static' %>
                        <%= f.text_field :business_name, class: "form-control" %>
                        <%= f.field_error :business_name %>
                    </div>
                    <div class="form-group">
                        <%= f.label :tradename, class: 'bmd-label-static' %>
                        <%= f.text_field :tradename, class: "form-control" %>
                        <%= f.field_error :tradename %>
                    </div>
                    <div class="form-group">
                        <%= f.label :rfc, class: 'bmd-label-static' %>
                        <%= f.text_field :rfc, class: "form-control" %>
                        <%= f.field_error :rfc %>
                    </div>
                    <div class="form-group">
                        <%= f.label :address, class: 'bmd-label-static' %>
                        <%= f.text_field :address, class: "form-control" %>
                        <%= f.field_error :address %>
                    </div>
                    <div class="form-group">
                        <%= f.label :street, class: 'bmd-label-static' %>
                        <%= f.text_field :street, class: "form-control" %>
                        <%= f.field_error :street %>
                    </div>
                    <div class="form-group">
                        <%= f.label :suburb, class: 'bmd-label-static' %>
                        <%= f.text_field :suburb, class: "form-control" %>
                        <%= f.field_error :suburb %>
                    </div>
                    <div class="form-group">
                        <%= f.label :responsable, class: 'bmd-label-static' %>
                        <%= f.text_field :responsable, class: "form-control" %>
                        <%= f.field_error :responsable %>
                    </div>
                    <div class="form-group">
                        <%= f.label :responsible_phone, class: 'bmd-label-static' %>
                        <%= f.text_field :responsible_phone, class: "form-control" %>
                        <%= f.field_error :responsible_phone %>
                    </div>
                    <div class="form-group">
                        <%= f.label :email, class: 'bmd-label-static' %>
                        <%= f.text_field :email, class: "form-control" %>
                        <%= f.field_error :email %>
                    </div>
                    <div class="form-group">
                        <%= f.label :notification_mail, class: 'bmd-label-static' %>
                        <%= f.text_field :notification_mail, class: "form-control" %>
                        <%= f.field_error :notification_mail %>
                    </div>
                    <div class="form-group">
                        <%= f.label :general_description, class: 'bmd-label-static' %>
                        <%= f.text_field :general_description, class: "form-control" %>
                        <%= f.field_error :general_description %>
                    </div>
                    
                    
                </div>
            </div>
        </div>
    </div>
    
    <br>
    

    <br>
    <%= f.submit 'Guardar', :class => 'btn btn-raised btn-primary float-right' %>
<% end %>

app/views/providers/_provider.html.erb
 <tr>
    <td><%= provider.business_name %></td>
    <td><%= provider.tradename %></td>
    <td><%= provider.rfc %></td>
    <td><%= provider.address %></td>
    <td><%= provider.street %></td>
    <td><%= provider.suburb %></td>
    <td><%= provider.responsable %></td>
    <td><%= provider.responsible_phone %></td>
    <td><%= provider.email %></td>
    <td><%= provider.notification_mail %></td>
    <td><%= provider.general_description %></td>

app/views/providers/index.html.erb
<h1>Proveedores</h1>
<%= link_to t('Agregar'), new_provider_path, class: "btn btn-primary float-right" %>

 <table class="table">
      <thead>
        <tr>
            <th>Razon social</th>
            <th>Nombre Comercial</th>
            <th>RFC</th>
            <th>Direccion</th>
            <th>Calle</th>
            <th>Colonia</th>
            <th>CP</th>
            <th>Responsable</th>
            <th>Correo Electronico</th>
            <th>Correo Notificaciones</th>
            <th>Descripcion Gral</th>
        </tr>
      </thead>
      <tbody>
        <%= render @providers %>
      </tbody>
  </table>

app/views/providers/new.html.erb
<h1>Nuevo Proveedor</h1>
<%= render 'form' %>