config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    path: '', # optional namespace or empty string for no space
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'secret',
      confirmation: 'verification',
      registration: 'register',
      sign_up: 'signup'
    }

  devise_scope :user do
    authenticated :user do
      root 'insureds#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  

  resources :insureds, only: %i[index new create show] do
    resources :contacts, only: %i[index new create show]
    resources :addresses
    resources :orders
  end
  resources :orders, only: %i[index]
  resources :insured_records, only: [:new, :create]
  resources :pre_opinions
  resources :opinions
  resources :doctors
  resources :providers
  resources :treatments
  resources :raw_materials
  # resources :sections, only: %i[new create]

  resources :users, only: %i[index new create edit update]
  
  get 'pages/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :insured

  validates :street, presence: true
  validates :interior_number, presence: true
  validates :outdoor_number, presence: true
  validates :postal_code, presence: true
  validates :suburb, presence: true
  validates :reference, presence: true

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :order
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :insured

  validates :name, presence: true
  validates :relation, presence: true
  validates :phone, presence: true
  validates :cell_phone, presence: true
  validates :email, presence: true
  validates :notes, presence: true

  accepts_nested_attributes_for :insured

end

app/models/contact_info.rb
class ContactInfo < ApplicationRecord
  belongs_to :insured
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    has_many :treatments
    has_many :insureds, through: :treatments
    
    validates :name, 
        :last_name, 
        :mother_last_name, 
        :mobile,
        :mail,
        presence: true 
    
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :order
end

app/models/insured.rb
class Insured < ApplicationRecord
    has_one :contact_info
    has_many :treatments
    has_many :doctors, through: :treatments
    
    has_many :contacts
    has_many :addresses
    has_many :orders
    
    validates :name, presence: true 
    validates :last_name, presence: true 
    validates :mother_last_name, presence: true 
    validates :gender, presence: true 
    validates :birth_date, presence: true 
    validates :policy, presence: true 
end

app/models/insured_record.rb
class InsuredRecord
    include ActiveModel::Model

    attr_accessor(
        :name, 
        :last_name, 
        :mother_last_name, 
        :gender, 
        :birth_date, 
        :street, 
        :interior_number, 
        :outdoor_number, 
        :postal_code, 
        :suburb
    )
    validates :name, presence: true 
    validates :last_name, presence: true 
    validates :mother_last_name, presence: true 
    validates :gender, presence: true 
    validates :birth_date, presence: true 
    validates :street, presence: true 
    validates :interior_number, presence: true 
    validates :outdoor_number, presence: true 
    validates :postal_code, presence: true 
    validates :suburb, presence: true 

    
    def save
        return false if invalid?

        ActiveRecord::Base.transaction do
            insured = Insured.create!(name: name, 
                last_name: last_name, mother_last_name: mother_last_name, 
                gender: gender, birth_date: birth_date)
            insured.create_contact_info!(
                street: street, 
                interior_number: interior_number, 
                outdoor_number: outdoor_number, 
                postal_code: postal_code, 
                suburb: suburb
            )
        end

        true

    rescue ActiveRecord::StatementInvalid => e
        # Handle exception that caused the transaction to fail
        # e.message and e.cause.message can be helpful
        errors.add(:base, e.message)
        false
    end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :order
  belongs_to :raw_material
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :insured
  has_many :comments
  has_many :documents
  
  has_many :items
  has_many :raw_materials, through: :items
  accepts_nested_attributes_for :raw_materials
end

app/models/provider.rb
class Provider < ApplicationRecord
    validates :business_name, presence: true 
    validates :tradename, presence: true
    validates :rfc, presence: true
    validates :address, presence: true
    validates :street, presence: true
    validates :suburb, presence: true
    validates :responsable, presence: true
    validates :responsible_phone, presence: true
    validates :email, presence: true
    validates :notification_mail, presence: true
    validates :general_description, presence: true
    
end

app/models/raw_material.rb
class RawMaterial < ApplicationRecord
  belongs_to :unit_measurement
  belongs_to :raw_material_group
  belongs_to :raw_material_family

  has_many :items
  has_many :orders, through: :items
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/section.rb
class Section < ApplicationRecord
    has_one :user
    
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  belongs_to :insured
  belongs_to :doctor
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :section
end

app/controllers/insureds_controller.rb
class InsuredsController < ApplicationController
    protect_from_forgery except: %i[index]

    def index
        @insureds = Insured.all()
        respond_to do |format|
            format.js { render json: @insureds, status: :ok }
            format.html
        end 
    end

    def new
        @insured = Insured.new 
    end

    def create
        #render plain: params[:insured].inspect
        @insured = Insured.new insured_params
        if @insured.save
            return redirect_to @insured
        end
        render :new
    end

    def show
        @insured = Insured.find params[:id]
    end

    private

    def insured_params
        params.require(:insured).permit! 
    end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/insureds_helper.rb
module InsuredsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/insureds/_form.html.erb
<%= form_for @insured, builder: CustomFormBuilder do |f| %>
    <%= f.form_error %>

    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
        <%= f.field_error :name %>
    </div>
    <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: "form-control" %>
        <%= f.field_error :last_name %>
    </div>
    <div class="form-group">
        <%= f.label :mother_last_name %>
        <%= f.text_field :mother_last_name, class: "form-control" %>
        <%= f.field_error :mother_last_name %>
    </div>
    <div class="form-group">
        <%= f.label :gender %>
        <%= f.text_field :gender, class: "form-control" %>
        <%= f.field_error :gender %>
    </div>
    <div class="form-group">
        <%= f.label :birth_date %>
        <%= f.date_field :birth_date, class: "form-control" %>
        <%= f.field_error :birth_date %>
    </div>
    <div class="form-group">
        <%= f.label :policy %>
        <%= f.text_field :policy, class: "form-control" %>
        <%= f.field_error :policy %>
    </div>

    <%= f.submit 'Guardar', :class => 'btn btn-raised btn-primary float-right' %>
<% end %>

app/views/insureds/index.html.erb
<br>
<%= link_to t('.link_to'),new_insured_path, class: "btn btn-primary float-right" %>
<br>
<%= react_component("InsuredList", { insureds: @insureds }) %>

app/views/insureds/new.html.erb
<h2>Nuevo Asegurado</h2>
<h5>Datos Generales</h5>
<%= render 'form' %>

app/views/insureds/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">Asegurado</li>
  </ol>
</nav>
<div class="row">
    <div class="col-9">
        <div class="jumbotron">
            <h2 class="display-4">Asegurado</h2>
            <h3 style="text-decoration: underline">
                <%= @insured.name %> <%= @insured.last_name %> <%= @insured.mother_last_name %>
            </h3>
            <hr class="my-4">
            <p><strong>GÉNERO: </strong> <%= @insured.gender %> </p>
            <p><strong>NACIÓ EL: </strong> <%= @insured.birth_date %> </p>
            <p><strong>POLIZA: </strong> <%= @insured.policy %> </p>
            <p><strong>MODULO: </strong> </p>
            <p><strong>TIPO DE SERVICIO:  </p>
            <p><strong>TIPO DE SOLICITUD:  </p>
            <p><strong>CIUDAD DE RESIDENCIA: </p>
            <p><strong>COASEGURO: </strong>  </p>
            <p><strong>FOLIO GNP: </strong> </p>
        </div>
    </div>
    <div class="col-3">
        <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
            <a class="nav-link active">
                FICHA PERSONAL
            </a>
            <%= link_to 'CONTACTOS', insured_contacts_url(@insured) , class: "nav-link" %>
            
            <%= link_to 'DIRECCIONES',insured_addresses_url(@insured) , class: "nav-link" %>
            
            <%= link_to 'SOLICITUDES',new_insured_order_url(@insured) , class: "nav-link" %>
            
        </div>
    </div>
</div>