config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    path: '', # optional namespace or empty string for no space
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'secret',
      confirmation: 'verification',
      registration: 'register',
      sign_up: 'signup'
    }

  devise_scope :user do
    authenticated :user do
      root 'insureds#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  

  resources :insureds, only: %i[index new create show] do
    resources :contacts, only: %i[index new create show]
    resources :addresses
    resources :orders
  end
  resources :orders, only: %i[index]
  resources :insured_records, only: [:new, :create]
  resources :pre_opinions
  resources :opinions
  resources :doctors
  resources :providers
  resources :treatments
  resources :raw_materials
  # resources :sections, only: %i[new create]

  resources :users, only: %i[index new create edit update]
  
  get 'pages/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :section
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  # skip_before_filter :require_no_authentication
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: %i[edit update]

    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new user_params
        if params[:permissions]
            params[:permissions].map { |permission|
                @user.add_role permission.to_sym
            }
        end
        if @user.save
            return redirect_to users_url
        end
        render :new
    end

    def edit
    end

    def update
        @user.roles.map { |role| 
            @user.remove_role role.name.to_sym
        }
        if params[:permissions]
            params[:permissions].map { |permission|
                @user.add_role permission.to_sym
            }
        end
        if @user.update user_params
            return redirect_to users_url
        end
        render :edit
    end

    private
    def set_user
        @user = User.find params[:id]
    end
    def user_params
        params.require(:user).permit!
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, builder: CustomFormBuilder do |f| %>
    <%= f.form_error %>
    <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control" %>
        <%= f.field_error :email %>
    </div>
    <div class="form-group">
        <%= f.label :section_id %><br />
        <%= f.select :section_id, Section.all.collect { |p| [ p.name, p.id ] } , {:include_blank=> "Selecciona"},{:class => "form-control"} %>
        <%= f.field_error :section_id %>
    </div>
    <%- if @user.new_record?%>
        <div class="form-group">
            <%= f.label :password %>
            <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> characters minimum)</em>
            <% end %><br />
            <%= f.password_field :password, autocomplete: "new-password", class: "form-control"%>
            <%= f.field_error :password %>
        </div>
    <% end %>
    <div class="jumbotron">
        <h3 class="display-6">Permisos</h3>
        <hr class="my-4">
        <div class="form-check">
            <%= check_box_tag 'permissions[]', 'insureds', @user.has_role?(:insureds), class: "form-check-input" %>
            <%= label_tag 'Asegurados', nil , class:"form-check-label"  %>
        </div>
        <div class="form-check">
            <%= check_box_tag 'permissions[]', 'orders', @user.has_role?(:orders), class: "form-check-input" %>
            <%= label_tag 'Solicitudes', nil , class:"form-check-label"  %>
        </div>
        <div class="form-check">
            <%= check_box_tag 'permissions[]', 'users', @user.has_role?(:users), class: "form-check-input" %>
            <%= label_tag 'Usuarios', nil , class:"form-check-label"  %>
        </div>
        <div class="form-check">
            <%= check_box_tag 'permissions[]', 'providers', @user.has_role?(:providers), class: "form-check-input" %>
            <%= label_tag 'Proveedores', nil , class:"form-check-label"  %>
        </div>
        
    </div>
    <%= f.submit 'Guardar', :class => 'btn btn-raised btn-primary float-right' %>
<% end %>

app/views/users/_user.html.erb
<tr>
    <th>
    <%= user.email %>
    </th>
    <th>
        <%- user.roles.each do |role| %>
            <%- case role.name %>
            <% when "insureds" %>
                <i class="fas fa-user-injured fa-2x"></i>
            <% when "orders" %>
                <i class="fas fa-file-signature fa-2x"></i>
            <% when "users" %>
                <i class="fas fa-users fa-2x"></i>
            <% else %>
                <i class="fas fa-truck fa-2x"></i>
            <% end  %>
        <% end %>
    </th>
    <th>
        <%= link_to 'Editar', edit_user_url(user) %>
    </th>
</tr>

app/views/users/edit.html.erb
<h1>Editar Usuario</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Usuarios</h1>
<%= link_to 'Nuevo Usuario', new_user_url, class: "btn btn-primary float-right" %>
<br/><br/>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>email</th>
      <th>Permisos</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <%= render @users %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Nuevo usuario</h1>

<%= render 'form' %>