config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    path: '', # optional namespace or empty string for no space
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'secret',
      confirmation: 'verification',
      registration: 'register',
      sign_up: 'signup'
    }

  devise_scope :user do
    authenticated :user do
      root 'insureds#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  

  resources :insureds, only: %i[index new create show] do
    resources :contacts, only: %i[index new create show]
    resources :addresses
    resources :orders
  end
  resources :orders, only: %i[index]
  resources :insured_records, only: [:new, :create]
  resources :pre_opinions
  resources :opinions
  resources :doctors
  resources :providers
  resources :treatments
  resources :raw_materials
  # resources :sections, only: %i[new create]

  resources :users, only: %i[index new create edit update]
  
  get 'pages/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :insured

  validates :street, presence: true
  validates :interior_number, presence: true
  validates :outdoor_number, presence: true
  validates :postal_code, presence: true
  validates :suburb, presence: true
  validates :reference, presence: true

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :order
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :insured

  validates :name, presence: true
  validates :relation, presence: true
  validates :phone, presence: true
  validates :cell_phone, presence: true
  validates :email, presence: true
  validates :notes, presence: true

  accepts_nested_attributes_for :insured

end

app/models/contact_info.rb
class ContactInfo < ApplicationRecord
  belongs_to :insured
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    has_many :treatments
    has_many :insureds, through: :treatments
    
    validates :name, 
        :last_name, 
        :mother_last_name, 
        :mobile,
        :mail,
        presence: true 
    
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :order
end

app/models/insured.rb
class Insured < ApplicationRecord
    has_one :contact_info
    has_many :treatments
    has_many :doctors, through: :treatments
    
    has_many :contacts
    has_many :addresses
    has_many :orders
    
    validates :name, presence: true 
    validates :last_name, presence: true 
    validates :mother_last_name, presence: true 
    validates :gender, presence: true 
    validates :birth_date, presence: true 
    validates :policy, presence: true 
end

app/models/insured_record.rb
class InsuredRecord
    include ActiveModel::Model

    attr_accessor(
        :name, 
        :last_name, 
        :mother_last_name, 
        :gender, 
        :birth_date, 
        :street, 
        :interior_number, 
        :outdoor_number, 
        :postal_code, 
        :suburb
    )
    validates :name, presence: true 
    validates :last_name, presence: true 
    validates :mother_last_name, presence: true 
    validates :gender, presence: true 
    validates :birth_date, presence: true 
    validates :street, presence: true 
    validates :interior_number, presence: true 
    validates :outdoor_number, presence: true 
    validates :postal_code, presence: true 
    validates :suburb, presence: true 

    
    def save
        return false if invalid?

        ActiveRecord::Base.transaction do
            insured = Insured.create!(name: name, 
                last_name: last_name, mother_last_name: mother_last_name, 
                gender: gender, birth_date: birth_date)
            insured.create_contact_info!(
                street: street, 
                interior_number: interior_number, 
                outdoor_number: outdoor_number, 
                postal_code: postal_code, 
                suburb: suburb
            )
        end

        true

    rescue ActiveRecord::StatementInvalid => e
        # Handle exception that caused the transaction to fail
        # e.message and e.cause.message can be helpful
        errors.add(:base, e.message)
        false
    end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :order
  belongs_to :raw_material
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :insured
  has_many :comments
  has_many :documents
  
  has_many :items
  has_many :raw_materials, through: :items
  accepts_nested_attributes_for :raw_materials
end

app/models/provider.rb
class Provider < ApplicationRecord
    validates :business_name, presence: true 
    validates :tradename, presence: true
    validates :rfc, presence: true
    validates :address, presence: true
    validates :street, presence: true
    validates :suburb, presence: true
    validates :responsable, presence: true
    validates :responsible_phone, presence: true
    validates :email, presence: true
    validates :notification_mail, presence: true
    validates :general_description, presence: true
    
end

app/models/raw_material.rb
class RawMaterial < ApplicationRecord
  belongs_to :unit_measurement
  belongs_to :raw_material_group
  belongs_to :raw_material_family

  has_many :items
  has_many :orders, through: :items
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/section.rb
class Section < ApplicationRecord
    has_one :user
    
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  belongs_to :insured
  belongs_to :doctor
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :section
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recupera</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Compiled and minified JavaScript -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body id="page-top">
  
  <%# <nav class="navbar navbar-light bg-light">
    <a class="navbar-brand" href="#"> %>
    <%# <%= image_tag ('Logo.png'), height: '64', width: '128' %>
   <%# </a>
  </nav> %>
  <div id="wrapper">
      <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
      
        <%= image_tag ('logo_white.png'), class: 'nav_logo', id: 'nav_logo' %>

      </a>
      <br/><br/>
      <!-- Nav Item - Pages Collapse Menu -->
      <%- if current_user.has_role?(:insureds) or current_user.has_role?(:orders)%>
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseOperations" aria-expanded="true" aria-controls="collapseOperations">
          <span>OPERACIÓN</span>
        </a>
        <div id="collapseOperations" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <%- if current_user.has_role?(:insureds) %>
              <%= link_to 'Asegurados', insureds_url, class: 'collapse-item' %>
            <% end %>
            <%- if current_user.has_role?(:orders) %>
              <%= link_to 'Seguimiento', orders_path, class: 'collapse-item' %>
              <%= link_to 'Pre-dictamen', pre_opinions_path, class: 'collapse-item' %>
              <%= link_to 'Dictamen', opinions_path, class: 'collapse-item' %>
              <%= link_to 'Información', '#', class: 'collapse-item' %>
              <%= link_to 'Cambiar receta', '#', class: 'collapse-item' %>
              <%= link_to 'Pendiente asegurado', '#', class: 'collapse-item' %>
            <% end %>
          </div>
        </div>
      </li>
    <% end %>

    
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseAdministration" aria-expanded="true" aria-controls="collapseAdministration">
          <span>ADMINISTRACION</span>
        </a>
        <div id="collapseAdministration" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
              <%= link_to 'Usuarios', users_url, class: 'collapse-item' %>            
          </div>
        </div>
      </li>
      

      <%- if current_user.has_role?(:providers) %>
        <li class="nav-item">
          <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseProvider" aria-expanded="true" aria-controls="collapseProvider">
            <span>PROVEEDOR</span>
          </a>
          <div id="collapseProvider" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
              <%= link_to 'Proveedores', providers_url, class: 'collapse-item' %>
            </div>
          </div>
        </li>
      <% end %>

      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseQuery" aria-expanded="true" aria-controls="collapseQuery">
          <span>CONSULTA</span>
        </a>
        <div id="collapseQuery" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            
          </div>
        </div>
      </li>

      

     

      
      

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>


    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>


          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">
            <!-- Nav Item - Alerts -->
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">3+</span>
              </a>
              <!-- Dropdown - Alerts -->
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                  Alerts Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-primary">
                      <i class="fas fa-file-alt text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 12, 2019</div>
                    <span class="font-weight-bold">A new monthly report is ready to download!</span>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-success">
                      <i class="fas fa-donate text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 7, 2019</div>
                    $290.29 has been deposited into your account!
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-warning">
                      <i class="fas fa-exclamation-triangle text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 2, 2019</div>
                    Spending Alert: We've noticed unusually high spending for your account.
                  </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
              </div>
            </li>

           

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">
                  <%= current_user.email %>
                </span>
                <img class="img-profile rounded-circle" src="https://api.adorable.io/avatars/285/abott@adorable.png">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Settings
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                  Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <%= link_to('Logout', destroy_user_session_path, class: "dropdown-item", method: :delete) %>  
                  
                
              </div>
            </li>

          </ul>

        </nav>

    <div class="container-fluid">
      <%= yield %>
    </div>

    </div>

    </div>
  </body>
</html>

app/views/layouts/landing_page.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Recupera</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Compiled and minified JavaScript -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body class="landingPage">

    <%= yield %>

</body>
</html>